refactor(pingcap/tidb): refactor two merged tests to prow sytle
PingCAP-QE/ci pull request #1685
Opened 2023-01-03 10:25 UTC by purelind

refactor some merged-pipelines to prow style

* merged_integration_copr_test
* merged_tiflash_test

2023-01-03 14:07 UTC, wuhuizuo requested changes

2023-01-03 14:36 UTC, purelind commented on pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
> +                        docker build -t hub.pingcap.net/qa/tidb:${REFS.base_ref} -f Dockerfile .
here run tiflash test with docker-compose file, need build tidb image with current commit hash

2023-01-04 02:31 UTC, lijie0123 commented on pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
> +                        docker build -t hub.pingcap.net/qa/tidb:${REFS.base_ref} -f Dockerfile .
Is Dockerfile is in tiflash repo？ Will the docker image be pushed?

2023-01-04 03:41 UTC, purelind commented on pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
> +                        docker build -t hub.pingcap.net/qa/tidb:${REFS.base_ref} -f Dockerfile .
1. I have update here to use dockerfile from https://github.com/PingCAP-QE/artifacts/tree/main/dockerfiles.
2. tidb image that been built here not push to registry, only for current test.

2023-01-04 03:49 UTC, wuhuizuo commented
/lgtm
/approve

2023-01-04 03:50 UTC, wuhuizuo approved these changes

2023-01-04 03:50 UTC, merged