feat(pingcap/tidb): support more integration pipeline in VerfiyCI of tidb lts branches
PingCAP-QE/ci pull request #3060
Opened 2024-08-06 10:39 UTC by wuhuizuo

- release-6.1
- release-6.5

Fixes #3057
Fixes #3059

Signed-off-by: wuhuizuo <wuhuizuo@126.com>

2024-08-06 10:51 UTC, purelind commented on jobs/pingcap/tidb/release-6.1/pull_integration_br_test.groovy
There is already a pull_br_integration_test, no need to add a new one here.

2024-08-06 10:56 UTC, purelind requested changes

2024-08-06 10:56 UTC, purelind commented on jobs/pingcap/tidb/release-6.1/pull_integration_lightning_test.groovy
This branch's lightning pipeline has not been split, so this pipeline is not needed.

2024-08-06 10:56 UTC, purelind commented on jobs/pingcap/tidb/release-6.5/pull_integration_br_test.groovy
please delete this，pull_br_ingration_test alreay exist

2024-08-06 10:56 UTC, purelind commented on jobs/pingcap/tidb/release-6.5/pull_integration_lightning_test.groovy
This branch's lightning pipeline has not been split, so this pipeline is not needed, please delete this

2024-08-06 10:56 UTC, purelind commented on pipelines/pingcap/tidb/release-6.1/pod-pull_e2e_test.yaml
> +    - name: report
please remove this unused container `report`

2024-08-06 10:56 UTC, purelind commented on pipelines/pingcap/tidb/release-6.1/pod-pull_integration_copr_test.yaml
> +    - name: report
please remove this unused container report

2024-08-06 10:56 UTC, purelind commented on pipelines/pingcap/tidb/release-6.1/pod-pull_common_test.yaml
> +      image: "hub.pingcap.net/jenkins/centos7_golang-1.21:latest"
go version is go1.20，please update to `hub.pingcap.net/jenkins/centos7_golang-1.20:latest`

2024-08-06 10:56 UTC, purelind commented on pipelines/pingcap/tidb/release-6.1/pod-pull_e2e_test.yaml
> +      image: "hub.pingcap.net/jenkins/centos7_golang-1.21:latest"
go version is go1.20，please update to hub.pingcap.net/jenkins/centos7_golang-1.20:latest

2024-08-06 10:56 UTC, purelind commented on pipelines/pingcap/tidb/release-6.5/pod-pull_common_test.yaml
> +      image: "hub.pingcap.net/jenkins/centos7_golang-1.21:latest"
go version is go1.20，please update to hub.pingcap.net/jenkins/centos7_golang-1.20:latest

2024-08-07 02:43 UTC, purelind commented on prow-jobs/pingcap/tidb/release-6.5-presubmits.yaml
> +      branches: *branches
Please remove those lines. Not exist lighting pipelines in 6.5(br & lightning are in the same dir)

2024-08-07 02:44 UTC, purelind requested changes

2024-08-07 02:44 UTC, purelind commented on prow-jobs/pingcap/tidb/release-6.1-presubmits.yaml
> +      branches: *branches
Please remove those lines. This branch's lightning pipeline has not been split from br, so this pipeline is not needed.

2024-08-07 02:46 UTC, wuhuizuo commented on prow-jobs/pingcap/tidb/release-6.1-presubmits.yaml
> +      branches: *branches
```suggestion
```

2024-08-07 02:47 UTC, wuhuizuo commented on prow-jobs/pingcap/tidb/release-6.5-presubmits.yaml
> +      branches: *branches
```suggestion
```

2024-08-07 02:55 UTC, purelind approved these changes
/lgtm

2024-08-07 02:56 UTC, merged